name: Python application

on: [push]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: List changed python files
        id: list_changed_python_files
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin main
          files="$(git diff --name-only --diff-filter=AM origin/main | grep '.py$' | tr '\n' ' ')"
          if [ -n "${files}" ]; then
            echo "files=${files}" | tee >> "$GITHUB_OUTPUT"
          fi

      - name: Install requirements
        if: steps.list_changed_python_files.outputs.files != null
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Black
        if: steps.list_changed_python_files.outputs.files != null
        run: |
          black --check ${{ steps.list_changed_python_files.outputs.files }}

      - name: Flake8
        if: steps.list_changed_python_files.outputs.files != null
        run: |
          flake8 --max-line-length=89  ${{ steps.list_changed_python_files.outputs.files }}

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openscad
          version: 1.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_dev.txt

      - name: Run tests
        run: |
          coverage run --source solid_node -m pytest
          coverage report -m

  build:
    runs-on: ubuntu-latest
    needs: test

    env:
      SOLID_NODE_VERSION: "${{ github.ref }}"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_dev.txt

      - name: Build python package
        run: |
          make dist

      - name: Detect package version
        id: package_version
        run: |
          from setuptools.extern.packaging import version
          try:
            solid_node_version = str(version.parse("$GITHUB_OUTPUT"))
            print(f"version={solid_node_version}", file=open("$GITHUB_OUTPUT", "a"), flush=True)
          except Exception as e:
            pass
        shell: python

      - name: Create release
        uses: actions/create-release@v1
        if: steps.package_version.outputs.version != null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package_version.outputs.version }}
          release_name: ${{ steps.package_version.outputs.version }}
          draft: false
          prerelease: false
